### ISSUE TITLE
Extraction of THOR package failed.

### ISSUE THREAD

**Issue by lp33pp66** [NextronSystems/nextron-helper-scripts#4] opened 2023-07-10 03:43 UTC
I executed the `thunderstorm-installer.sh` script and successfully downloaded the `/opt/nextron/thunderstorm/thor.zip` file. However, when I extracted the contents of the archive, I encountered an error stating `Invalid License - Reason: The given license is unknown (possibly a legacy issue).`

**Comment by redteampanda-ng** [comment] 2023-07-10 05:16
Hi,

are you a customer and do you have a valid license? If yes, please reach out to our support team via support@nextron-systems.com with your customer ID and a quick text what the issue is.

Thanks

**Comment by redteampanda-ng** [comment] 2023-07-10 10:38
Hi @lp33pp66,

I will go ahead and close this issue now. Thunderstorm will not work with a THOR Lite license and needs a special license.

**Closed by redteampanda-ng** 2023-07-10 10:38 UTC
